name: Build and Deploy NextJS app

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/checkout@v3
        with: 
          node-version: 18.3.0
          cache: npm
      
      - name: Build
        run: |
          ls website-portfolio-code
          npm ci
